name: barbershop

version: 0.0.1+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg_provider: ^1.0.3
  get: ^4.6.1
  core:
    path: ../smartbarber-core-app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/barber.svg
    - assets/json/delete.json
    - assets/json/info.json
    - assets/json/loading.json
